# Generated by Django 3.2 on 2022-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('person', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
